name: Deployment Success Check

on:
    pull_request:
        branches: ["main"]
        types: [opened, synchronize, reopened, closed]
    workflow_dispatch:

jobs:
    build_test:
      uses: ./.github/workflows/build.yml
      with: {}
    
    check_success:
      runs-on: ubuntu-latest
      needs: build_test
      steps:
        - name: Check Deployment Success
          run: |
            if [ "${{ needs.build_test.outputs.success }}" == "true" ]; then
              echo "Deployment was successful."
            else
              echo "Deployment failed."
              exit 1
            fi
    
    
        
              