name: Deployment Success Check

on:
    pull_request:
        branches: ["main"]
        types: opened
    workflow_dispatch:

jobs:
    deployment_check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Ruby
              uses: ruby/setup-ruby@086ffb1a2090c870a3f881cc91ea83aa4243d408 #v1.254.0
              with:
                ruby-version: '3.4' # Not needed with a .ruby-version file
                bundler-cache: true # runs 'bundle install' and caches installed gems automatically
                cache-version: 0
            # - name: Setup Pages
            #   id: pages
            #   uses: actions/configure-pages@v5
            - name: Check Deployment
              run: bundle exec jekyll build
              env:
               JEKYLL_ENV: production
            - name: Verify Deployment
              run: |
                if [ ! -d "_site" ]; then
                    echo "Deployment failed: _site directory not found."
                    exit 1
                fi
                echo "Deployment check passed: _site directory exists."
              